replicaCount:
  backend: 1
  frontend: 1
image:
  backend:
    repository: vourteen14/heypico-backend
    pullPolicy: Always
    tag: "staging"
  frontend:
    repository: vourteen14/heypico-frontend
    pullPolicy: Always
    tag: "staging"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  backend:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: heypico-staging.local
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  tls: []
resources:
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  frontend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
externalSecret:
  secretStore: "heypico-secretstore"
  refreshInterval: "1h"
  vault:
    path: "heypico-backend"
database:
  existingSecret: "postgres-secret"
env:
  backend:
    NODE_ENV: "production"
    HOST: "0.0.0.0"
    PORT: "3000"
  frontend:
    VUE_APP_API_URL: "http://heypico-staging.local/api"
healthCheck:
  backend:
    enabled: true
    path: "/health"
    initialDelaySeconds: 30
    periodSeconds: 10
  frontend:
    enabled: true
    path: "/"
    initialDelaySeconds: 15
    periodSeconds: 10