apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heypico-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=docker.io/vourteen14/heypico-backend,frontend=docker.io/vourteen14/heypico-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: staging
    argocd-image-updater.argoproj.io/frontend.update-strategy: staging
spec:
  project: default
  source:
    repoURL: https://github.com/vourteen14/test-ci-cd-frontend.git
    path: helm-charts
    targetRevision: staging
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.frontend.repository
          value: docker.io/vourteen14/heypico-frontend
        - name: image.frontend.tag
          value: staging
        - name: image.backend.repository
          value: docker.io/vourteen14/heypico-backend
        - name: image.backend.tag
          value: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: heypico
  syncPolicy:
    automated:
      prune: true
      selfHeal: true