apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heypico-web-app.fullname" . }}-backend
  labels:
    {{- include "heypico-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.backend }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "heypico-web-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heypico-web-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heypico-web-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.backend.targetPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.database.existingSecret }}
          {{- if .Values.healthCheck.backend.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.backend.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.backend.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.backend.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.backend.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.backend.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.backend.periodSeconds }}
            timeoutSeconds: 3
            failureThreshold: 3
          {{- end }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}