apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "heypico-web-app.fullname" . }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heypico-web-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.database.existingSecret }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        NODE_ENV: "{{ `{{ .NODE_ENV }}` }}"
        HOST: "{{ `{{ .HOST }}` }}"
        PORT: "{{ `{{ .PORT }}` }}"        
        DB_HOST: "{{ `{{ .DB_HOST }}` }}"
        DB_PORT: "{{ `{{ .DB_PORT }}` }}"
        DB_NAME: "{{ `{{ .DB_NAME }}` }}"
        DB_USER: "{{ `{{ .DB_USER }}` }}"
        DB_PASSWORD: "{{ `{{ .DB_PASSWORD }}` }}"
  data:
  - secretKey: NODE_ENV
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: NODE_ENV
  - secretKey: HOST
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: HOST
  - secretKey: PORT
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: PORT      
  - secretKey: DB_HOST
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: DB_HOST
  - secretKey: DB_PORT
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: DB_PORT
  - secretKey: DB_NAME
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: DB_NAME
  - secretKey: DB_USER
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: {{ .Values.externalSecret.vault.path }}
      property: DB_PASSWORD