apiVersion: v1
kind: Service
metadata:
  name: {{ include "heypico-web-app.fullname" . }}-backend
  labels:
    {{- include "heypico-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "heypico-web-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend