apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: heypico-secretstore
  namespace: heypico
spec:
  provider:
    vault:
      server: "https://vault.karuhun.cloud"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
